<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Vacancies\Module'                         => __DIR__ . '/Module.php',
    'Vacancies\Controller\VacanciesController' => __DIR__ . '/src/Vacancies/Controller/VacanciesController.php',
);
