<?php
/** @var array $languages */
/** @var string $title */
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<div class="row"></div>
<p>
    <a href="<?php echo $this->url('languages', array('action'=>'add'));?>">Добавить язык</a>
</p>

<table class="table">
    <tr>
        <th>Метка</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($languages as $language) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($language['name']);?></td>
            <td>
                <a href="<?php echo $this->url('languages',
                    array('action'=>'edit', 'id' => $language['id']));?>">Редактировать</a>
                <a href="<?php echo $this->url('languages',
                    array('action'=>'delete', 'id' => $language['id']));?>">Удалить</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
