<?php
/** @var array $departments */
/** @var string $title */
/** @var array $filter */
/** @var Vacancies\Form\FilterForm $form */
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<div class="row">
<?php
    $form->setAttribute('method', 'get');
    $form->prepare();
    echo $this->form()->openTag($form);
    echo $this->formRow($form->get('languages')->setValue($filter['language']));
    echo $this->formRow($form->get('submit'));
    echo $this->form()->closeTag();
?>
</div>
<p>
    <a href="<?php echo $this->url('departments', array('action'=>'add'));?>">Добавить отдел</a>
</p>

<table class="table">
    <tr>
        <th>Отдел</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($departments as $department) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($department['title']);?></td>
            <td>
                <a href="<?php echo $this->url('departments',
                    array('action'=>'edit', 'id' => $department['id']));?>">Редактировать</a>
                <a href="<?php echo $this->url('departments',
                    array('action'=>'delete', 'id' => $department['id']));?>">Удалить</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
